
const { SlashCommandBuilder } = require('@discordjs/builders');
const { MessageEmbed } = require('discord.js');
const humanizeDuration = require('humanize-duration')
const moment = require('moment')

module.exports = {
    setupRequired: false,
    category: "Anti-Raid",
    data: new SlashCommandBuilder()
    .setName('antiraid')
    .setDescription('Affiche les informations des modules d\'antiraid.'),

    async run(client, interaction) {

        const antiRaid = new MessageEmbed()
            .setColor(client.config.discord.color)
            .setAuthor({ name: interaction.guild.name, iconURL: interaction.guild.iconURL() })
            .setTitle(`Information des modules de l'anti-raid.`)
            .addField("Anti ajout de bot :", `**Status : **${client.guildSettings[interaction.guild.id]["addBot"].status ? "Activé" : "Désactivé"}.\n**Whitelist : **${client.guildSettings[interaction.guild.id]["addBot"].whitelist.length != 0 ? client.guildSettings[interaction.guild.id]["addBot"].whitelist.map(role => interaction.guild.roles.cache.get(role)) : "Aucun"}.\n**Sanction : **${client.guildSettings[interaction.guild.id]["addBot"].sanction}.\n**Tentative : **${client.guildSettings[interaction.guild.id]["addBot"].times}.\n**Durée : **${humanizeDuration(moment(client.guildSettings[interaction.guild.id]["addBot"].duration), { units: ["m", "s"], round: true, language: "fr", largest: 2, delimiter: " et "})}.`, true)
            .addField("Anti everyone :", `**Status : **${client.guildSettings[interaction.guild.id]["everyone"].status ? "Activé" : "Désactivé"}.\n**Whitelist : **${client.guildSettings[interaction.guild.id]["everyone"].whitelist.length != 0 ? client.guildSettings[interaction.guild.id]["everyone"].whitelist.map(role => interaction.guild.roles.cache.get(role)) : "Aucun"}.\n**Sanction : **${client.guildSettings[interaction.guild.id]["everyone"].sanction}.\n**Tentative : **${client.guildSettings[interaction.guild.id]["everyone"].times}.\n**Durée : **${humanizeDuration(moment(client.guildSettings[interaction.guild.id]["everyone"].duration), { units: ["m", "s"], round: true, language: "fr", largest: 2, delimiter: " et "})}.`, true)
            .addField("Anti liens :", `**Status : **${client.guildSettings[interaction.guild.id]["link"].status ? "Activé" : "Désactivé"}.\n**Whitelist : **${client.guildSettings[interaction.guild.id]["link"].whitelist.length != 0 ? client.guildSettings[interaction.guild.id]["link"].whitelist.map(role => interaction.guild.roles.cache.get(role)) : "Aucun"}.\n**Sanction : **${client.guildSettings[interaction.guild.id]["link"].sanction}.\n**Tentative : **${client.guildSettings[interaction.guild.id]["link"].times}.\n**Durée : **${humanizeDuration(moment(client.guildSettings[interaction.guild.id]["link"].duration), { units: ["m", "s"], round: true, language: "fr", largest: 2, delimiter: " et "})}.`, true)
            .addField("Anti spam :", `**Status : **${client.guildSettings[interaction.guild.id]["spam"].status ? "Activé" : "Désactivé"}.\n**Whitelist : **${client.guildSettings[interaction.guild.id]["spam"].whitelist.length != 0 ? client.guildSettings[interaction.guild.id]["spam"].whitelist.map(role => interaction.guild.roles.cache.get(role)) : "Aucun"}.\n**Sanction : **${client.guildSettings[interaction.guild.id]["spam"].sanction}.\n**Tentative : **${client.guildSettings[interaction.guild.id]["spam"].times}.\n**Durée : **${humanizeDuration(moment(client.guildSettings[interaction.guild.id]["spam"].duration), { units: ["m", "s"], round: true, language: "fr", largest: 2, delimiter: " et "})}.`, true)
            .addField("Anti ban en masse :", `**Status : **${client.guildSettings[interaction.guild.id]["massBan"].status ? "Activé" : "Désactivé"}.\n**Whitelist : **${client.guildSettings[interaction.guild.id]["massBan"].whitelist.length != 0 ? client.guildSettings[interaction.guild.id]["massBan"].whitelist.map(role => interaction.guild.roles.cache.get(role)) : "Aucun"}.\n**Sanction : **${client.guildSettings[interaction.guild.id]["massBan"].sanction}.\n**Tentative : **${client.guildSettings[interaction.guild.id]["massBan"].times}.\n**Durée : **${humanizeDuration(moment(client.guildSettings[interaction.guild.id]["massBan"].duration), { units: ["m", "s"], round: true, language: "fr", largest: 2, delimiter: " et "})}.`, true)
            .addField("Anti kick en masse :", `**Status : **${client.guildSettings[interaction.guild.id]["massKick"].status ? "Activé" : "Désactivé"}.\n**Whitelist : **${client.guildSettings[interaction.guild.id]["massKick"].whitelist.length != 0 ? client.guildSettings[interaction.guild.id]["massKick"].whitelist.map(role => interaction.guild.roles.cache.get(role)) : "Aucun"}.\n**Sanction : **${client.guildSettings[interaction.guild.id]["massKick"].sanction}.\n**Tentative : **${client.guildSettings[interaction.guild.id]["massKick"].times}.\n**Durée : **${humanizeDuration(moment(client.guildSettings[interaction.guild.id]["massKick"].duration), { units: ["m", "s"], round: true, language: "fr", largest: 2, delimiter: " et "})}.`, true)
            .addField("Anti webhook :", `**Status : **${client.guildSettings[interaction.guild.id]["webhooks"].status ? "Activé" : "Désactivé"}.\n**Whitelist : **${client.guildSettings[interaction.guild.id]["webhooks"].whitelist.length != 0 ? client.guildSettings[interaction.guild.id]["webhooks"].whitelist.map(role => interaction.guild.roles.cache.get(role)) : "Aucun"}.\n**Sanction : **${client.guildSettings[interaction.guild.id]["webhooks"].sanction}.\n**Tentative : **${client.guildSettings[interaction.guild.id]["webhooks"].times}.\n**Durée : **${humanizeDuration(moment(client.guildSettings[interaction.guild.id]["webhooks"].duration), { units: ["m", "s"], round: true, language: "fr", largest: 2, delimiter: " et "})}.`, true)
            .addField("Anti création de salons :", `**Status : **${client.guildSettings[interaction.guild.id]["channelCreate"].status ? "Activé" : "Désactivé"}.\n**Whitelist : **${client.guildSettings[interaction.guild.id]["channelCreate"].whitelist.length != 0 ? client.guildSettings[interaction.guild.id]["channelCreate"].whitelist.map(role => interaction.guild.roles.cache.get(role)) : "Aucun"}.\n**Sanction : **${client.guildSettings[interaction.guild.id]["channelCreate"].sanction}.\n**Tentative : **${client.guildSettings[interaction.guild.id]["channelCreate"].times}.\n**Durée : **${humanizeDuration(moment(client.guildSettings[interaction.guild.id]["channelCreate"].duration), { units: ["m", "s"], round: true, language: "fr", largest: 2, delimiter: " et "})}.`, true)
            .addField("Anti supression de salons :", `**Status : **${client.guildSettings[interaction.guild.id]["channelDelete"].status ? "Activé" : "Désactivé"}.\n**Whitelist : **${client.guildSettings[interaction.guild.id]["channelDelete"].whitelist.length != 0 ? client.guildSettings[interaction.guild.id]["channelDelete"].whitelist.map(role => interaction.guild.roles.cache.get(role)) : "Aucun"}.\n**Sanction : **${client.guildSettings[interaction.guild.id]["channelDelete"].sanction}.\n**Tentative : **${client.guildSettings[interaction.guild.id]["channelDelete"].times}.\n**Durée : **${humanizeDuration(moment(client.guildSettings[interaction.guild.id]["channelDelete"].duration), { units: ["m", "s"], round: true, language: "fr", largest: 2, delimiter: " et "})}.`, true)
            .setThumbnail(interaction.guild.iconURL())
            .setTimestamp()
            .setFooter({ text: `${client.user.username} • ${client.config.discord.footer}`, iconURL: client.user.avatarURL })   
            
        interaction.reply({ embeds: [antiRaid], ephemeral: true })  
    }
}